In [1]:
#P3pcaExampleF23
#PCA example
import numpy as np
from numpy import linalg as LA
import tensorflow as tf


In [2]:

X = np.array([[7,4,3],[4,1,8],[6,3,5],[8,6,1],[8,5,7],[7,2,9],[5,3,3],[9,5,8],[7,4,5],[8,2,2]])#define array
print (X)
print (X.T)  #print the transpose
Xmean = np.mean(X,0)  # compute mean vector
print (Xmean)

[[7 4 3]
 [4 1 8]
 [6 3 5]
 [8 6 1]
 [8 5 7]
 [7 2 9]
 [5 3 3]
 [9 5 8]
 [7 4 5]
 [8 2 2]]
[[7 4 6 8 8 7 5 9 7 8]
 [4 1 3 6 5 2 3 5 4 2]
 [3 8 5 1 7 9 3 8 5 2]]
[6.9 3.5 5.1]


In [3]:
C = np.cov(X.T)  #transpose is matrix we want to work with - compute covariance matrix
print (C)

[[ 2.32222222  1.61111111 -0.43333333]
 [ 1.61111111  2.5        -1.27777778]
 [-0.43333333 -1.27777778  7.87777778]]


In [24]:
w, v = LA.eig(C)  # get the eigenvalues w and the eigenvectors 
print (w)
print (v)

[0.74992815 3.67612927 8.27394258]
[[-0.70172743  0.69903712 -0.1375708 ]
 [ 0.70745703  0.66088917 -0.25045969]
 [ 0.08416157  0.27307986  0.95830278]]


In [26]:
A  = np.array([v[:,2],v[:,1]])  # form the transformation matrix using eigenvectors
# for the top two eigenvalues
print(A)

[[-0.1375708  -0.25045969  0.95830278]
 [ 0.69903712  0.66088917  0.27307986]]


In [27]:
Y = np.matmul(A,(X-Xmean).T) # Apply transformation to obtain new   
                             # data representation in 2-D
print(Y)

[[-2.15142276  3.80418259  0.15321328 -4.7065185   1.29375788  4.0993133
  -1.62582148  2.11448986 -0.2348172  -2.74637697]
 [-0.17311941 -2.88749898 -0.98688598  1.30153634  2.27912632  0.1435814
  -2.23208282  3.2512433   0.37304031 -1.06894049]]


In [30]:
xhat = np.matmul(A.T,Y).T + Xmean  #recover the original data using the inverse transform
print(xhat)

[[7.07495606 3.92443193 2.99101016]
 [4.35818659 0.63888882 7.95704095]
 [6.18905239 2.80940399 4.97732603]
 [8.45730172 5.53896441 0.94515359]
 [8.31521059 4.68221571 6.96219527]
 [6.43642293 2.56817868 9.06759253]
 [5.56335682 2.43204338 2.93243389]
 [8.88184769 5.11911702 8.01417058]
 [7.19307301 3.80535054 4.97684382]
 [6.53059219 3.48140552 2.17623319]]


In [31]:
mse = np.sum((X - xhat)**2)/10  #mean squared error
print(mse)

0.6749353375153229
